version: '3.5'

services:
  backend:
    image: example-backend
    build: '../../part1/example-app/backend/'
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000


  frontend:
    image: example-frontend
    build: '../../part1/example-app/frontend/'
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
