version: '3.5'

services:
  backend:
    image: example-backend
    build: './backend/'
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    ports:
      - 8080:8080


  # NOTE: Frontend needs to be built each time the container runs, not optimal but ensures the env variable for the backend URL gets applied each time
  # Await for the "INFO: Accepting connetions..." message from the frontend container before navigating to localhost
  frontend:
    image: example-frontend
    build: 
      context: './frontend/'
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080


  redis:
    image: redis:6.2.5
