version: '3.5'

services:
  km-frontend:
    image: ml-km-frontend
    build: 
      context: ./ml-kurkkumopo-frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  km-backend:
    image: ml-km-backend
    build:
      context: ./ml-kurkkumopo-backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - km-training
    volumes:
      - model:/src/model
      

  km-training:
    image: ml-km-training
    build:
      context: ./ml-kurkkumopo-training/
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data


volumes:
  model:
  imgs:
  data:
